### ISSUE TITLE
openalpr counts a single search as 2

### ISSUE THREAD

**Issue by ghost** [openalpr/cloudapi#13]
When requesting a response from the api using the URL, the response shows that 2 searches were used from the available credits, even if there is only a single licence plate in the image. Is there any reason for this? I cannot see it documented anywhere.

Thanks,
Mike

**Comment by gtjnewell** [comment]
If you have recognize_vehicle set to 1, then the api call with incur an additional credit. See: http://doc.openalpr.com/api/cloudapi.html

---joe

**Comment by ghost** [comment]
@gtjnewell thanks for that, for some reason I couldn't find that page in the docs, not looking hard enough :( makes sense now, thanks 👍
